
'''
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the fib_sum of the even-valued terms.
'''
def fib_sum_even_fibonacci(limit):
    fib_sum = 0

    a = 1
    b = 2
    hold = 0
    while a < limit:
        if not b%2:
            fib_sum+=b

        hold = a+b
        a = b
        b = hold

    return fib_sum

def main():
    print("result: ", fib_sum_even_fibonacci(400))



if __name__ == "__main__":
  main()
